### ISSUE TITLE
Not all asterisks removed from card names

### ISSUE THREAD

**Issue by magreenblatt** [taw/magic-preconstructed-decks#7]
The code in `lib/deck.rb` removes a single asterisk suffix from a card name, but does not remove multiple asterisks. For example, `data/theme/5dn/Nuts and Bolts.txt` [1] has cards with both single and double asterisk suffixes.

What do the asterisks represent? Is the intent to remove all asterisks?

[1] https://github.com/taw/magic-preconstructed-decks/blob/master/data/theme/5dn/Nuts%20and%20Bolts.txt

**Comment by taw** [comment]
Well, [you can see for yourself](http://www.wizards.com/magic/displaythemedeck.asp?set=5dn&decknum=1&lang=en). A lot of old decklists had that for reprint information. We're currently stripping that but keeping it in source data on an off-chance that it will be of some use.

I didn't notice double asterisks before, I guess they got stripped at some later stage by indexer, [since they're not there on mtg.wtf](http://mtg.wtf/deck/5dn/nuts-and-bolts).

**Comment by taw** [comment]
Fixed now

**Comment by magreenblatt** [comment]
Thanks for the explanation. The asterisks seem to indicate cards that are included in the deck from previous sets. Perhaps the number of asterisks indicate different sets (e.g. cards with 1 asterisk are from previous set A, and cards with 2 asterisks are from previous set B).
